### ISSUE TITLE
Make use of BearerAuthorizationTrait

### ISSUE THREAD

**Issue by shadowhand** [Edwin-Luijten/oauth2-strava#2]
[`BearerAuthorizationTrait`](https://github.com/thephpleague/oauth2-client/blob/master/src/Tool/BearerAuthorizationTrait.php) can be used to replace [this code](https://github.com/Edwin-Luijten/oauth2-strava/blob/2cfeca5f6fa89be5e7f10e1f088fded9da53482c/src/Provider/Strava.php#L112). The additional headers defined there can be set by overloading [`getDefaultHeaders`](https://github.com/thephpleague/oauth2-client/blob/51ab7174d12a13643c57cd4d97c2325c4788b55c/src/Provider/AbstractProvider.php#L802).

**Comment by Edwin-Luijten** [comment]
Fixed by https://github.com/Edwin-Luijten/oauth2-strava/commit/8c7d5db4ec26a1c2aae65f418f0ac4e056dd5956
