### ISSUE TITLE
Resource owner fetch should not need to define access token in query

### ISSUE THREAD

**Issue by shadowhand** [Edwin-Luijten/oauth2-strava#3]
Is it necessary to [defined the `access_token` query parameter](https://github.com/Edwin-Luijten/oauth2-strava/blob/2cfeca5f6fa89be5e7f10e1f088fded9da53482c/src/Provider/Strava.php#L48) when fetching resource owner? This should be handled automatically by `getAuthorizationHeaders`.

**Comment by Edwin-Luijten** [comment]
Fixed by https://github.com/Edwin-Luijten/oauth2-strava/commit/8c7d5db4ec26a1c2aae65f418f0ac4e056dd5956

**Comment by fbonzon** [comment]
@shadowhand is correct. 8c7d5db did improve the code, but not fix the original concern of this issue. I address it #5
